page_blocks: []
_array_structures:
  page_blocks:
    - label: Banner
      icon: article
      value:
       _id: banner
       title: Banner
       heading1: This is a heading
       heading2: This is a heading
       heading3: This is a heading
       image: https://source.unsplash.com//DuD5D3lWC3c
     - label: text-columns
      icon: article
      value:
       _id: text-columns
       title: Text Columns
       column1: This is text
       column2: This is text
       column3: This is text
     - label: gallery
      icon: article
      value:
       _id: gallery
       image1:
       image2:
       image3:
       image4:
       image5:
       image6: