page_blocks: []
_array_structures:
  page_blocks:
    - label: Banner
      icon: article
      value:
       _id: banner
       title: Banner
       heading1: This is a heading
       heading2: This is a heading
       heading3: This is a heading
       image: https://source.unsplash.com//DuD5D3lWC3c
    - label: text-columns
      icon: article
      value:
       _id: text-columns
       title: Text Columns
       column1: This is text
       column2: This is text
       column3: This is text
    - label: gallery
      icon: article
      value:
       _id: gallery
       title: Gallery
       gallery:
        - image_url: https://source.unsplash.com/8muZ_2cfX4A
        - image_url: https://source.unsplash.com/8muZ_2cfX4A
        - image_url: https://source.unsplash.com/8muZ_2cfX4A
        - image_url: https://source.unsplash.com/8muZ_2cfX4A
        - image_url: https://source.unsplash.com/8muZ_2cfX4A
        - image_url: https://source.unsplash.com/8muZ_2cfX4A
    - label: text
      icon: article
      value:
       _id: text
       title: Text
       heading: This is a heading
       text: This is text
    - label: video
      icon: article
      value:
       _id: video
       title: Video
       video: https://www.youtube.com/embed/fUn1w3Vfh6U
       heading: This a a heading
       text: this is text
       